site_name: DSP-INGEST

nav:
  - Overview:
      - Introduction: introduction.md
      - API documentation:
          - Endpoints: api-endpoints.md
          - Authentication: api-authentication.md

plugins:
  - include-markdown
  - search
  - git-revision-date

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
